name: Test Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main,dev ]

jobs:
  simple-test:
    runs-on: ubuntu-latest
    steps:
      - name: Start Job
        run: echo "Starting job..."

      - name: First Task
        run: |
          echo "Running first task"
          sleep 10
          echo "First task completed"

      - name: Second Task
        run: |
          echo "Running second task"
          sleep 5
          echo "Second task completed"

      - name: Finish Job
        run: echo "Job completed successfully!"
