name: Test Workflow
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: |
          echo "Running test..."
          sleep 30
          echo "Test completed!"

      - name: Build
        run: |
          echo "Starting build..."
          sleep 20
          echo "Build completed!"
